import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + 'bg-white'}>
        <nav className='p-2 bg-[#5582a9] text-white text-center underline'>
          <Link href="/dashboard">Dashboard</Link>
        </nav>
        <main className="min-w-screen min-h-screen items-center justify-between pt-12 py-24 px-6">
          {children}
        </main>
      </body>
    </html>
  )
}
